#日志
logging:
  config: classpath:logback.xml

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true  #驼峰命名转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      capital-mode: true


spring:
  profiles:
    active: test
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50
    
# 不拦截直接放行URL
ignore:
  urls:
    - /user/login
    - /mini/login
    - /wx/bindWx
    - /mobile/login
    - /wx/login
    - /revokeToken
    - /actuator/**
    - /log/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger-resources/configuration/ui
    - /swagger-resources/configuration/security
    - /v2/api-docs
    - /resources/**
    - /webjars/**
    - /doc.html
    - /systenant/getTenant
    - /validata/smsCode/**
    - /sys/sysSms/createCode
    - /sys/sysSms/checkCode
    - /sysUser/forgetPassword







#book:
#  xxljob:
#    ### 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；//http://127.0.0.1:8001/xxl-job-admin
#    admin:
#      addresses: http://localhost:8080/xxl-job-admin
#    executor:
#      ### 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
#      appName: xxl-job-executor-book
#      ### 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
#      ip:
#      ### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
#      port: 9995
#      ### 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
#      logpath: ../logs/xxl-job/book
#      ### 执行器日志保存天数 [选填] ：值大于3时生效，启用执行器Log文件定期清理功能，否则不生效；
#      logretentiondays: -1
#    ### 执行器通讯TOKEN [选填]：非空时启用；
#    accessToken:

